commands:
  # Time
  - command:
    input: What time is it
    entity: time
    action: getTime
  - command:
    input: Tell me the time
    entity: time
    action: getTime
  # Date
  - command:
    input: What date is it
    entity: time
    action: getDate
  - command:
    input: Tell me the date.
    entity: time
    action: getDate
  # Year
  - command:
    input: Tell me the year
    entity: time
    action: getYear
  - command:
    input: Which year is it
    entity: time
    action: getYear
  # Open
  - command:
    input: open google
    entity: open
    action: Chrome
  - command:
    input: start google
    entity: open
    action: Chrome
  - command:
    input: Open music
    entity: open
    action: soundcloud











  
